In [ ]:
import pandas as pd

mutations_file = '../datasets/mutation_distribution_in_lineages.txt'

threshold = 0.99
gamma = ['P.1'] #Gamma
alpha = ['BA.1.1.7'] # Alpha
omicron = ['BA.1.1.529', 'BA.1','BA.2'] # Omicron
mutations_df = pd.read_table(mutations_file, sep='\t', usecols=['Lineage',
                                                                    'Frequency of mutated sequences per Lineage',
                                                                    'Genome position',
                                                                    'Ref seq',
                                                                    'ut seq'])
                                                                    
mutations = mutations_df[(mutations_df['Lineage'].isin(sum([gamma,alpha,omicron],[]))) & (mutations_df['Frequency of mutated sequences per Lineage'] >= threshold)]

In [4]:
mutations

,Frequency of mutated sequences per Lineage,Lineage,Genome position,Ref seq,ut seq
54410,0.995240,BA.1,14408,C,T
54413,0.991896,BA.1,10029,C,T
54446,0.995566,BA.1,23403,A,G
54447,0.990729,BA.1,23525,C,T
54474,0.990348,BA.1,8393,G,A
55634,0.991150,BA.1.1.7,10029,C,T
55672,0.993117,BA.1.1.7,23403,A,G
58182,0.994994,BA.2,14408,C,T
58183,0.993588,BA.2,17410,C,T
58185,0.992587,BA.2,10029,C,T
58214,0.996946,BA.2,23403,A,G
58215,0.995168,BA.2,23525,C,T
58221,0.996308,BA.2,24424,A,T
58222,0.996189,BA.2,24469,T,A
58223,0.992156,BA.2,26060,C,T
58229,0.990902,BA.2,2790,C,T
118848,0.993259,P.1,14408,C,T
118864,0.998197,P.1,23403,A,G
118865,0.992730,P.1,23525,C,T
118870,0.990741,P.1,25088,G,T
118875,0.990569,P.1,26149,T,C
118879,0.990669,P.1,28512,C,G
118894,0.995120,P.1,5648,A,C
141412,0.992134,BA.1.1.7,3037,C,T
188081,0.994215,BA.1,3037,C,T
188082,0.991406,BA.1,5386,T,G
188091,0.990394,BA.1,13195,T,C
188098,0.995811,BA.2,3037,C,T
188103,0.994696,BA.2,12880,C,T
188104,0.993514,BA.2,15714,C,T
188710,0.994719,P.1,3037,C,T

In [5]:
ls = mutations['Genome position'].to_list()
ls = list(set(ls))
ls.sort()
ls

[2790,
 3037,
 5386,
 5648,
 8393,
 10029,
 12880,
 13195,
 14408,
 15714,
 17410,
 23403,
 23525,
 24424,
 24469,
 25088,
 26060,
 26149,
 28512]